export let movesList = {
  TACKLE: {
    name: "TACKLE",
    power: 35,
    accuracy: 95,
    effect: "none",
    type: "NORMAL",
  },
  GROWL: {
    name: "GROWL",
    power: "none",
    accuracy: 100,
    effect: "ENEMY ATTACK STAT LOWER",
    type: "NORMAL",
  },
  "LEECH SEED": {
    name: "LEECH SEED",
    power: "none",
    accuracy: 90,
    effect: "SEEDED",
    type: "GRASS",
  },
  "VINE WHIP": {
    name: "VINE WHIP",
    power: 35,
    accuracy: 100,
    effect: "none",
    type: "GRASS",
  },
  SCRATCH: {
    name: "SCRATCH",
    power: 40,
    accuracy: 100,
    effect: "none",
    type: "NORMAL",
  },
  EMBER: {
    name: "EMBER",
    power: 40,
    accuracy: 100,
    effect: "MAY BURN",
    type: "FIRE",
  },
  "METAL CLAW": {
    name: "METAL CLAW",
    power: 50,
    accuracy: 95,
    effect: "MAY USER ATTACK STAT RISE",
    type: "STEEL",
  },
  "TAIL WHIP": {
    name: "TAIL WHIP",
    power: "none",
    accuracy: 100,
    effect: "ENEMY DEFENSE STAT LOWER",
    type: "NORMAL",
  },
  BUBBLE: {
    name: "BUBBLE",
    power: 20,
    accuracy: 100,
    effect: "MAY ENEMY SPEED STAT LOWER",
    type: "WATER",
  },
  WITHDRAW: {
    name: "WITHDRAW",
    power: "none",
    accuracy: 100,
    effect: "USER DEFENSE STAT RAISE",
    type: "WATER",
  },
};
